### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [Richbunks/prj-rev-bwfs-tea-cozy#1]
_Grade: Exceeds Expectations_

Fantastic job on your project - you met the design requirements to a tee! In terms of your code, you did a phenomenal job. You used `div` tags in a meaningful way and your organizational skills really show off in the way you wrote your HTML. An area for improvement here, albeit a minor one, is the usage of the class tag - in some instances. Remember that classes are only used when more than one instance of that styling occurs, if not, opt for `id`. In addition to this, try to remember using semantic tags when possible, in HTML5 there exists a `<footer>` tag that you could of used for your footer instead.

A recommendation here is to review this article in case you're still confused. Aside from this detail you really did an amazing job 🥇 
[id vs. class](https://css-tricks.com/the-difference-between-id-and-class/)

**Comment by Richbunks** [comment]
Thanks some good constructive comments, I'll try to take onboard for the next project.
